<?php
return [
	'blank-button' => [ 'title' => __('Blank Button', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'blank-image' => [ 'title' => __('Blank Image', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'blog-archive' => [ 'title' => __('Blog Archive', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'border-divider' => [ 'title' => __('Border Divider', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'button-banner' => [ 'title' => __('Button Banner', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'contact' => [ 'title' => __('Contact', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'counter' => [ 'title' => __('Counter', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'cta-hero' => [ 'title' => __('Cta Hero', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'cta' => [ 'title' => __('Cta', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'decorated-text' => [ 'title' => __('Decorated Text', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'faq' => [ 'title' => __('Faq', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'gallery' => [ 'title' => __('Gallery', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'hero-slider' => [ 'title' => __('Hero Slider', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'icons' => [ 'title' => __('Icons', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'iframe' => [ 'title' => __('Iframe', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'list' => [ 'title' => __('List', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'logos' => [ 'title' => __('Logos', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'map' => [ 'title' => __('Map', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'motto-bar' => [ 'title' => __('Motto Bar', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'numbers' => [ 'title' => __('Numbers', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'offer' => [ 'title' => __('Offer', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'products' => [ 'title' => __('Products', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'program' => [ 'title' => __('Program', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'section-title' => [ 'title' => __('Section Title', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'shortcode' => [ 'title' => __('Shortcode', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'stats' => [ 'title' => __('Stats', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'subpage-hero' => [ 'title' => __('Subpage Hero', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'team' => [ 'title' => __('Team', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'testimonials' => [ 'title' => __('Testimonials', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'text-image-decorated' => [ 'title' => __('Text Image Decorated', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'text-images' => [ 'title' => __('Text Images', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'text-with-image' => [ 'title' => __('Text With Image', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'thank-you' => [ 'title' => __('Thank You', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'three-boxes' => [ 'title' => __('Three Boxes', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'three-columns-content' => [ 'title' => __('Three Columns Content', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'three-images' => [ 'title' => __('Three Images', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'two-buttons' => [ 'title' => __('Two Buttons', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'two-columns-list' => [ 'title' => __('Two Columns List', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'two-columns-text' => [ 'title' => __('Two Columns Text', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'two-images' => [ 'title' => __('Two Images', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'theme-form' => [ 'title' => __('Theme Form', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'flip-cards' => [ 'title' => __('Flip Cards', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
	'wyswig-content' => [ 'title' => __('Wyswig Content', 'ercodingtheme'), 'category' => 'ercodingtheme', 'align' => 'full' ],
];
